include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.gen.dart" # (Opcional) por si en el futuro hay archivos generados
    - "build/**" # Ignora carpeta build

linter:
  rules:
    # === Estilo de código ===
    - always_use_package_imports: true
    - prefer_single_quotes: true
    - require_trailing_commas: true
    - sort_child_properties_last: true
    - use_key_in_widget_constructors: true

    # === Buenas prácticas ===
    - avoid_print: true
    - prefer_const_constructors: true
    - prefer_final_locals: true
